-- V1__initial_schema.sql

-- 테이블 삭제 (존재하는 경우)
DROP TABLE IF EXISTS authority CASCADE;
DROP TABLE IF EXISTS board CASCADE;
DROP TABLE IF EXISTS board_hashtag CASCADE;
DROP TABLE IF EXISTS chat_room CASCADE;
DROP TABLE IF EXISTS chat_room_category CASCADE;
DROP TABLE IF EXISTS chat_room_member CASCADE;
DROP TABLE IF EXISTS chat_subject_category CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS hashtag CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS profile CASCADE;
DROP TABLE IF EXISTS profile_interest_tag CASCADE;

-- 테이블 생성
CREATE TABLE authority (
   authority_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   created_at TIMESTAMP(6) NOT NULL,
   member_id BIGINT,
   updated_at TIMESTAMP(6) NOT NULL,
   role VARCHAR(255) CHECK (role IN ('ROLE_USER','ROLE_ADMIN')),
   PRIMARY KEY (authority_id)
);

CREATE TABLE board (
   board_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   created_at TIMESTAMP(6) NOT NULL,
   member_id BIGINT NOT NULL,
   updated_at TIMESTAMP(6) NOT NULL,
   content VARCHAR(500) NOT NULL,
   PRIMARY KEY (board_id)
);

CREATE TABLE board_hashtag (
   board_hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   board_id BIGINT NOT NULL,
   hashtag_id BIGINT NOT NULL,
   PRIMARY KEY (board_hashtag_id)
);

CREATE TABLE chat_room (
   like_count INTEGER NOT NULL,
   chat_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   created_at TIMESTAMP(6) NOT NULL,
   last_message_message_id BIGINT UNIQUE,
   manager_id BIGINT NOT NULL,
   updated_at TIMESTAMP(6) NOT NULL,
   image_url VARCHAR(255),
   title VARCHAR(255) NOT NULL,
   PRIMARY KEY (chat_room_id)
);

CREATE TABLE chat_room_category (
    chat_room_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    chat_room_id BIGINT NOT NULL,
    chat_subject_category_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (chat_room_category_id),
    CONSTRAINT chat_room_category_unique UNIQUE (chat_room_id, chat_subject_category_id)
);

CREATE TABLE chat_room_member (
      chat_room_id BIGINT NOT NULL,
      chat_room_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      last_read_message_id BIGINT,
      member_id BIGINT NOT NULL,
      PRIMARY KEY (chat_room_member_id),
      CONSTRAINT chat_room_member_unique UNIQUE (chat_room_id, member_id)
);

CREATE TABLE chat_subject_category (
    chat_subject_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY (chat_subject_category_id)
);

CREATE TABLE comment (
     board_id BIGINT NOT NULL,
     created_at TIMESTAMP(6) NOT NULL,
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     member_id BIGINT NOT NULL,
     updated_at TIMESTAMP(6) NOT NULL,
     text VARCHAR(1000) NOT NULL,
     PRIMARY KEY (id)
);

CREATE TABLE hashtag (
     hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     tag VARCHAR(255) NOT NULL,
     PRIMARY KEY (hashtag_id)
);

CREATE TABLE member (
    created_at TIMESTAMP(6) NOT NULL,
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6) NOT NULL,
    email VARCHAR(255) UNIQUE,
    image_url VARCHAR(255),
    nickname VARCHAR(255),
    oauth2provider VARCHAR(255) CHECK (oauth2provider IN ('GOOGLE','NAVER')),
    password VARCHAR(255),
    PRIMARY KEY (member_id)
);

CREATE TABLE message (
     type SMALLINT NOT NULL CHECK (type BETWEEN 0 AND 2),
     chat_room_id BIGINT NOT NULL,
     created_at TIMESTAMP(6) NOT NULL,
     message_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     sender_id BIGINT NOT NULL,
     content VARCHAR(255) NOT NULL,
     PRIMARY KEY (message_id)
);

CREATE TABLE profile (
     birth DATE,
     created_at TIMESTAMP(6) NOT NULL,
     member_id BIGINT UNIQUE,
     profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     updated_at TIMESTAMP(6) NOT NULL,
     self_description VARCHAR(100),
     gender VARCHAR(255) CHECK (gender IN ('MAN','WOMAN','ETC')),
     image_url VARCHAR(255),
     mbti VARCHAR(255) CHECK (mbti IN ('INFP','ISFP','INTP','ISTP','ENFP','ESFP','ENTP','ESTP','INFJ','ISFJ','INTJ','ISTJ','ENFJ','ESFJ','ENTJ','ESTJ')),
     location GEOMETRY(Point, 4326),
     PRIMARY KEY (profile_id)
);

CREATE TABLE profile_interest_tag (
      profile_profile_id BIGINT NOT NULL,
      interest_tag VARCHAR(225)
);

-- 외래 키 추가
ALTER TABLE authority
    ADD CONSTRAINT FK_authority_member FOREIGN KEY (member_id) REFERENCES member;

ALTER TABLE board
    ADD CONSTRAINT FK_board_member FOREIGN KEY (member_id) REFERENCES member;

ALTER TABLE board_hashtag
    ADD CONSTRAINT FK_board_hashtag_board FOREIGN KEY (board_id) REFERENCES board,
    ADD CONSTRAINT FK_board_hashtag_hashtag FOREIGN KEY (hashtag_id) REFERENCES hashtag;

ALTER TABLE chat_room
    ADD CONSTRAINT FK_chat_room_message FOREIGN KEY (last_message_message_id) REFERENCES message,
    ADD CONSTRAINT FK_chat_room_member FOREIGN KEY (manager_id) REFERENCES member;

ALTER TABLE chat_room_category
    ADD CONSTRAINT FK_chat_room_category_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_room,
    ADD CONSTRAINT FK_chat_room_category_subject FOREIGN KEY (chat_subject_category_id) REFERENCES chat_subject_category;

ALTER TABLE chat_room_member
    ADD CONSTRAINT FK_chat_room_member_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_room,
    ADD CONSTRAINT FK_chat_room_member_member FOREIGN KEY (member_id) REFERENCES member;

ALTER TABLE comment
    ADD CONSTRAINT FK_comment_board FOREIGN KEY (board_id) REFERENCES board,
    ADD CONSTRAINT FK_comment_member FOREIGN KEY (member_id) REFERENCES member;

ALTER TABLE message
    ADD CONSTRAINT FK_message_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_room,
    ADD CONSTRAINT FK_message_member FOREIGN KEY (sender_id) REFERENCES member;

ALTER TABLE profile
    ADD CONSTRAINT FK_profile_member FOREIGN KEY (member_id) REFERENCES member;

ALTER TABLE profile_interest_tag
    ADD CONSTRAINT FK_profile_interest_tag_profile FOREIGN KEY (profile_profile_id) REFERENCES profile;

-- 인덱스 추가
CREATE INDEX idx_chat_room_member_member_id ON chat_room_member (member_id);
